# Generated by Django 3.2.6 on 2021-09-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'FeMale')], max_length=1),
        ),
    ]
